### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by Amin-Medbelle** [Stanko/react-slider#6]
This package is great, thanks for creating it. I strongly suggest to create it as an npm package though, it only takes 30 minutes top. If you want, I can create a PR for it.

**Comment by Stanko** [comment]
Hello @Amin-Medbelle,
I want to create a npm package, but it needs some heavy refactoring first. I kinda feel bad for releasing `React.createClass` and really old-school component. 

If you want, feel free to release it.

Hope that helps, cheers!

**Comment by Amin-Medbelle** [comment]
Ok, I'll start working on it and make a PR pretty soon.

**Comment by Amin-Medbelle** [comment]
The only issue is that there already is a react-slider on npm, could you please pick a name and let me know?

**Comment by Stanko** [comment]
Feel free to fork it and release it under whatever name you like 😄Then if I choose to do some refactoring it won't affect your package or fork.

Personally I would go for something along these lines - `simple-react-slider` or `small-react-slider`

**Comment by Amin52J** [comment]
I'll do the refactoring as well, actually I already have, it only needs to be released. (sorry I switched accounts 😄)

**Comment by Amin52J** [comment]
Just made a PR with all the changes #7 
I think it'd be wise if you release on npm under your name.

**Comment by Amin52J** [comment]
I just released the [npm package](https://www.npmjs.com/package/simple-react-slider) but under my name. It is still referencing to the original repo (obviously because it's a fork). Please let me know if you want me to make a new PR for it.
Also I think it'd be nice if you could add the npm package to the documents.
Thanks

**Comment by Stanko** [comment]
🎉🎉🎉
Good job!
